
export default function Head() {
  return (
    <>
      <title>FaceBook</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
      {/*//todo add your photo later */}
    </>
  )
}
